### ISSUE TITLE
Consolidate UseStaticFiles/UseFileServer into a single method

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/StaticFiles#10]
It should be a single method with options.

**Comment by borgdylan** [comment]
I switched from static files to file server just because only the latter allows me to enable directory browsing. If static files allowed this it might be easier to make them into one set of extensions.

**Comment by Bartmax** [comment]
Doesn't removing the `StaticFileOptions` makes it configure with something like

```
app.UseFileServer(new FileServerOptions()
{
    EnableDefaultFiles = false,
    ServeUnknownFileTypes = true,
    DefaultContentType = "text/plain"
});

```

That looks better than having 2 extension imho.

**Comment by muratg** [comment]
Putting this in RC2 for now.  We'll need to discuss the design, and can potentially punt this.

**Comment by muratg** [comment]
Wasn't designed. Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.

**Comment by shanselman** [comment]
Cough.
