### ISSUE TITLE
web.config with extensionless files

### ISSUE THREAD

**Issue by Yitzchok** [aspnet/StaticFiles#108]
I am not sure if this is the correct place to post this.

Adding a web.config file to a directory with staticContent of
```
  <staticContent>
             <mimeMap fileExtension = "." mimeType="text/json" />
  </staticContent>
```
Should allow the server to return extension less files on the server 

If you want to do this now you will have to set 
```
app.UseStaticFiles(new StaticFileOptions
{
ServeUnknownFileTypes = true
})
```

**Comment by Tratcher** [comment]
Those web.config settings configure the native IIS static file module. They have no affect on the managed Asp.Net static file middleware.  Asp.Net Core does not read anything from web.config (except HttpPlatformHandler).

**Comment by Yitzchok** [comment]
Ok thanks for explaining.
