### ISSUE TITLE
Add event for customizing file selection

### ISSUE THREAD

**Issue by Tratcher** [aspnet/StaticFiles#111]
Add an event at the beginning of the static file middleware when the request first arrives that would let you map any path to any file, and pick the content-type. Then the middleware could process that file normally (e-tags, if-modified-since, range, etc..).

**Comment by Eilon** [comment]
Moving to backlog as we're trying to limit new features at this time.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2456
