### ISSUE TITLE
Question: Is there a way to configure the static files to certain URLs / routes?

### ISSUE THREAD

**Issue by pebezo** [aspnet/StaticFiles#114]
I'm working with an ASP.NET Core app that's using Angular 2. In order for Angular to work I set up a fallback / catchall route that loads Angular stuff. I'm also using static files to serve the Angular bits as well as other assets.

The issue is that if wwwroot/assets/foo.css is missing the request goes on and the server returns the default Angular HTML page (instead of 404). Is there a way to tell StaticFile that paths that start with "/assets" or "/lib" or "/app" should be handled exclusively by StaticFile and not fall through if the file is not physically on disk?

Thanks

**Comment by pebezo** [comment]
This seems to work:

```
app.MapWhen(context =>
            {
                var path = context.Request.Path.Value;
                return path.StartsWith("/assets", StringComparison.OrdinalIgnoreCase) ||
                       path.StartsWith("/lib", StringComparison.OrdinalIgnoreCase) ||
                       path.StartsWith("/app", StringComparison.OrdinalIgnoreCase);
            }, config => config.UseStaticFiles());
```

Does it make sense to write this? Any unknown side-effects?

**Comment by Eilon** [comment]
Yup that's definitely a way to do it. You'll want to be a bit careful in case you have something like `/appetite_for_destruction`, which will still match your condition (it starts with `/app`). I'm sure @Tratcher has some thoughts on this (but he's out of the office this week).

**Comment by pebezo** [comment]
Good point. I should probably check if it starts with "/app/". Since I'm controlling the routes on the client side I don't think this would be an issue. I'm more concerned if it introduces some server-side overhead that's not immediately apparent (i.e. is it efficient). Thanks for the reply.

**Comment by muratg** [comment]
@pebezo Let us know if you have other questions/concerns!

**Comment by Tratcher** [comment]
You'd get similar results with
```
app.Map("/assets", subApp => subApp.UseStaticFiles());
app.Map("/lib", subApp => subApp.UseStaticFiles());
app.Map("/app", subApp => subApp.UseStaticFiles());
```
though you'd also have to tweak the file provider in that case as we don't have a simple overload for that yet: https://github.com/aspnet/StaticFiles/issues/57

Also, don't do your own path comparisons for exactly the reasons @Eilon said. Use PathString.StartsWithSegments: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L123
