### ISSUE TITLE
Option to look for default files at the root of wwwroot path only, not at subpath

### ISSUE THREAD

**Issue by NickAb** [aspnet/StaticFiles#115]
`DefaultFiles` middleware allows routing to default files at request subpath if no file was found, but for angular or other single page apps we would need to always route to `/wwwroot/index.html` for any subpath, i.e.:
- `http://localhost:5000/` -> `wwwroot/index.html`
- `http://localhost:5000/some-sub-path` -> `wwwroot/index.html`

Currently we have to write custom middleware to handle this case (see [stackoverflow](http://stackoverflow.com/questions/34628536/asp-net-5-angular-2-routing-template-page-not-reloading/34643314) for example). But it seems that adding option to `DefaultFiles` to route to `wwwroot` will be a good solution for such a common case.

https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/DefaultFilesMiddleware.cs#L67

**Comment by muratg** [comment]
@NickAb By "custom middleware" do you mean the example in http://stackoverflow.com/questions/31184446/asp-net-5-html5-history/34882405#34882405?

**Comment by NickAb** [comment]
For the moment I use this instead:
```cs
app.Use(async (context, next) =>
{
	await next();

	if (context.Response.StatusCode == 404 && IsGetOrHeadMethod(context.Request.Method))
	{
		context.Request.Path = "/"; // Put your Angular root page here 
		await next();
	}
});
```

Also there is an [Angular Middleware](https://github.com/a11smiles/AngularMiddleware/blob/master/AngularMiddleware/AngularRequestMiddleware.cs) on github.

**Comment by Tratcher** [comment]
Possibly related to https://github.com/aspnet/StaticFiles/issues/111

**Comment by Tratcher** [comment]
I think it would be an option like IncludeSubDirectories on PhysicalFileProvider.
