### ISSUE TITLE
GZipping files when running under IIS

### ISSUE THREAD

**Issue by poimis** [aspnet/StaticFiles#119]
There are (at least) three ways to serve gzipped content:
1. Pre-encoding (has its own issue #7 )
2. Write a middleware that takes care of compression
3. Rely on web-facing web server take care of the task

I tried the second option and found out that it doesn't really work under IIS, because StaticFileContext looks for IHttpSendFileFeature and if found, it delegates writing the file to it (effectively bypassing the middleware pipeline where I have the GZipMiddleware).

The problem here is, that the requested file still gets served uncompressed. Any ideas, how to get my static files compressed?

**Comment by Tratcher** [comment]
IHttpSendFileFeature is no longer available for IIS & Kestrel since Beta8, so that shouldn't be a problem. It's only supported by WebListener. IIS's dynamic compression should now kick in even for static files, or you can do it in middleware.

**Comment by poimis** [comment]
I am using rc1 and it definately does not work.

**Comment by jesterst** [comment]
Have same problem. Use Microsoft.AspNet.Server.Kestrel, version 1.0.0-rc1-final. GZipMiddleware not work.

**Comment by RehanSaeed** [comment]
If I also want to introduce caching, then my theory is that, surely it is better to cache the GZip'ed content. If I use IIS compression, then my caching is happening in my ASP.NET Core app and IIS is then GZip'ing the content each time for no reason.

**Comment by Eilon** [comment]
Moving to 1.0.1.

**Comment by AnderssonPeter** [comment]
Is this still the same? im running "Kestrel" (haven't tried with IIS) but my files seem to get gzipped by them self?

Am i totally confused or is this meant to happen? and if where does it happen?

**Comment by Tratcher** [comment]
Kestrel does not gzip files. IIS & IIS Express can do dynamic compression for any response.

**Comment by AnderssonPeter** [comment]
Checked again and its hosted in IIS Express but it says `Server: Kestrel` in the http header? why does it say `Kestrel` when its using IIS Express?

**Comment by davidfowl** [comment]
Because it's using both. IIS is a reverse proxy, in this scenario and Kestrel runs in your application's process.

**Comment by AnderssonPeter** [comment]
@davidfowl @Tratcher  Thanks i managed to run it without iis as a reverse proxy and then it didn't compress!

**Comment by spboyer** [comment]
Now that Microsoft.AspNet.ResponseCompression exists, is this a needed issue?

**Comment by oliverjanik** [comment]
This is an issue, I just ran into this today. Please reopen. It took me a while to debug.

Here are my observations:
1) Asp.Net Core gzips css and js bundles without any configuration
2) I've added ResponseCompression to also gzip static SVGs in my project:

```csharp
services.AddResponseCompression(o =>
{
    o.MimeTypes = new[] { "image/svg+xml" };
});
```
3) When I run this from with VS (IIS Express) I get my SVG's gzipped
4) Why I deploy and this runs under Win 2012 R2 under IIS which has static and dynamic compression OFF nothing is GZipped (not even the bundles)

My conclusion is that IIS acting as a proxy decompresses incoming requests and serves them plain.

Blank rule for dynamic compression ON is **NOT** an option because of [CRIME](https://en.wikipedia.org/wiki/CRIME).

**Comment by Tratcher** [comment]
@oliverjanik please open a new issue with details for your repro scenario.
