### ISSUE TITLE
Manage Cache-Control/Expires header more friendly

### ISSUE THREAD

**Issue by justdmitry** [aspnet/StaticFiles#122]
Currently `StaticFilesMiddleware` does not append `Cache-Control` and/or `Expires` headers to response. But managing browser cache is very important for static files.

Currently I use code in `Startup.cs` like this:
```
var staticFileOptions = new Microsoft.AspNet.StaticFiles.StaticFileOptions
{
    OnPrepareResponse = (context) =>
    {
        context.Context.Response.Headers.Add("Cache-Control", "public, max-age=15552000"); // 180 days
    }
};
app.UseStaticFiles(staticFileOptions);
```

It's too complex for simple scenario like 'set expiration on all static content'. I think `StaticFileOptions` should have one simple property like `DefaultCacheControl` for this.

**Comment by davidfowl** [comment]
That's too complex?

**Comment by justdmitry** [comment]
99% of static files in /wwwroot of 99% web sites need "non-empty" cache control. Additional property on top-level options class vs "lambda method that appends header to three-level-deeper collection" - I think first method is more friendly.

**Comment by andrewlock** [comment]
I agree, I feel like setting the cache headers should be a first class citizen in the `StaticFileOptions` class. It should be pretty easy to add a `CacheProfile` property to it, or potentially a `Func<CacheProfile, StaticFileResponseContext>`. This would greatly streamline this whole process, as well as avoiding typos by developers in the header values etc.

This could run just before the `OnPrepareResponse` method, and would use essentially the same behaviour as the [`ReponseCacheFilter`](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResponseCacheFilter.cs).

I've just had to create something like this manually so I think it would be very useful. I'd be happy to put together a pull request for it?

**Comment by davidfowl** [comment]
Not a fan of this change, using the typed headers for setting the cache if you want a strongly typed API.

**Comment by muratg** [comment]
We decided to not do this.  Thanks folks (and thanks @andrewlock for the PR.)

**Comment by RehanSaeed** [comment]
For anyone else who came here, @andrewlock raised a PR https://github.com/aspnet/StaticFiles/pull/157 to use the `CacheProfile` class to add `Cache-Control` and `Pragma` HTTP headers to static files.

The `ApplyCacheProfile(HttpContext, CacheProfile)` method @andrewlock has written in his PR is not something trivial and not something I'd want to include in my projects.

For anyone else who doesn't want to have to copy pasta his code, I've included it in the [Boilerplate.AspNetCore](https://www.nuget.org/packages/Boilerplate.AspNetCore/) NuGet package. The GitHub repo is [ASP-NET-MVC-Boilerplate/Framework](https://github.com/ASP-NET-MVC-Boilerplate/Framework).
