### ISSUE TITLE
StaticFiles middleware allocates 64kb buffer per file on windows

### ISSUE THREAD

**Issue by rynowak** [aspnet/StaticFiles#126]
Some allocation data collected from music store (using jmeter stress client):

![image](https://cloud.githubusercontent.com/assets/1430011/14619558/e9b52cda-056c-11e6-93f2-463101d47493.png)

`Win32FileStream` is allocating a 64kb buffer every time it's used.

This isn't necessarily bad, I just wanted to record the data point

**Comment by bbowyersmyth** [comment]
Related discussion https://github.com/dotnet/coreclr/issues/2223

**Comment by muratg** [comment]
@rynowak anything actionable on this, or did you want to track it for more investigation?

**Comment by rynowak** [comment]
Just logging/tracking it. We haven't done much testing yet with static files so I didn't want to lose the data point.

**Comment by pakrym** [comment]
This was fixed by https://github.com/aspnet/FileSystem/pull/216
