### ISSUE TITLE
Need some help with FileProviders. FileInfo.PhysicalPath returns the base path twice.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/StaticFiles#127]
I have a custom file provider that I register on ConfigureServices as:
```
services.AddSingleton(f => 
    new PhysicalFileProvider(Path.Combine(environment.WebRootPath, "../upfiles/")));
```
**note:** the path `../upfiles` prevents deleting user content uploded files because are outside wwwroot folder when a clean on the output (wwwroot folder) is needed.

Then on my cshtml I point to files as:
```
<img src="~/upfiles/somedir/somefile.jpg"/>
```

Now I'm trying to implement a TagHelper (but is not specific to taghelper), to resize the image file, so I need access to the physical path, get the stream, resize and return a different src path.

I can make it work hacking the directories. But looking at static file server I don't understand why this:

```
IFileInfo fileInfo = fileProvider.GetFileInfo(relative);
var physicalPath = fileInfo.PhysicalPath;
```

returns the base path twice: so the output of the `physycalPath` variable is:

```
C:\Development\Clients\xxx\xxx\src\xxx.Web\upfiles\upfiles\original\785f4415-a4aa-49a8-b394-42d2c3dcaa26.jpg
```

Note the double "upfiles" string there.

Is there a *safe* crossplat and consistent way to get from `"~/...."` -> to `"c:\...."`

FYI: On production, the FileProvider is switched to another FileProvider that uses AzureStorage. (in case you were wondering)

**Comment by muratg** [comment]
@Bartmax It's hard to say why "upfiles" shows up twice without knowing what your code does.  Perhaps debug and see where it's getting added the second time?

**Comment by muratg** [comment]
@Bartmax Any updates on your investigation?

**Comment by Bartmax** [comment]
Yes sorry forgot to describe it here.

The logic was like this:
ImageTagHelper:
check image source for: Src.StartsWith("~/upfiles");

then get FileProviderPath => fileInfo.PhysicalPath which returns:

`/upfiles/.....`

and I was replacing `~` from the src attribute with what I get from physicalPath, instead of `~/upfiles/` so the problem was simply that.

I'm still wondering if creating a new `TagHelper` is a good choice to go for implementing custom logic for ~ replacement ... if you have any thoughts on that, I will appreciate it.

I'm closing this for now, and sorry to forgot to do it before. Thanks!
