### ISSUE TITLE
Review FileExtensionContentTypeProvider and document the criteria for being included

### ISSUE THREAD

**Issue by Tratcher** [aspnet/StaticFiles#129]
`FileExtensionContentTypeProvider` contains the file extension to content-type mappings used by the `StaticFilesMiddleware`. Only extensions listed will be served by default. The original list was copied from IIS but we've made some additions.
- [ ] Review the APIs and make sure it's easy enough for people to add and remove entries.
- [ ] Document the criteria for including an entry in the default list.
- [ ] Review the current entries to make sure they meet the criteria.

@DamianEdwards

**Comment by DamianEdwards** [comment]
As part of the first item, I'd like to see what it would like to have an app set up to read a config file that specifies the file extension to content-type mappings, as an example.

**Comment by muratg** [comment]
Moving to post RTM for now. Ping me if you think this has to be done this week.

**Comment by Tragetaschen** [comment]
I've just tried to add a new file extension + content type to use with the file server.
There is definitely room for improvement:
```csharp
var fileExtensionContentTypeProvider = new FileExtensionContentTypeProvider();
fileExtensionContentTypeProvider.Mappings[".vtt"] = "text/vtt";
var options = new FileServerOptions();
options.StaticFileOptions.ContentTypeProvider = fileExtensionContentTypeProvider;

app.UseFileServer(options);
```

**Comment by Tratcher** [comment]
Policy considerations:
- Include file types included in other server's default sets
- Do not include file types likely to contain server-side code or configuration (e.g. cs, cshtml, json, etc..)
- Prefer mime types with well documented standards (e.g. RFCs)

This policy should be placed in the wiki and/or in a doc comment on FileExtensionContentTypeProvider

**Comment by Tratcher** [comment]
Adding/Removing file types has discoverability issues, but we haven't found a fix without breaking changes. Consider removing the IContentTypeProvider abstraction, it's rarely replaced.

**Comment by Tratcher** [comment]
@muratg recommend moving this to the 2.0 milestone for API breaking changes

**Comment by muratg** [comment]
@DamianEdwards @glennc Do we want to do this in 2.0.0? (We may need to as it could be a breaking change.)  If so, priority?

**Comment by muratg** [comment]
@Tratcher Backlogging this for now.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2454
