### ISSUE TITLE
Make "range" downloading functionality available outside of StaticFiles

### ISSUE THREAD

**Issue by mrahhal** [aspnet/StaticFiles#135]
So I have an Mvc core app running in production and I have an action that downloads a file using `PhysicalFileResult` which transmits the file directly. The files might be big so I wanted to support "range" downloading.

I was reading the StaticFiles middleware and it supports the specs perfectly so why would I have to implement it again outside of StaticFiles? Can't we make that functionality encapsulated and available to outside code? I thought about using `StaticFileContext` but it's internal anyway.

Then, we could make an Mvc `IActionResult` like `PhysicalFileResult` that supports "ranges".

**Comment by Tratcher** [comment]
Please Move this bug to MVC. It makes sense to add for some of this functionality to FileResult.

**Comment by mrahhal** [comment]
@Tratcher I agree, but I intentionally opened it here because simply adding the same functionality in Mvc would cause duplication, right? Should't there be a shared service? StaticFiles already has all the needed functionality (internally).

**Comment by Tratcher** [comment]
MVC is where you want the functionality. We'll figure out how to best get it there.

**Comment by mrahhal** [comment]
Alright I'll open one there, thanks.
