### ISSUE TITLE
UseFileServer requires AddDirectoryBrowser call in ConfigureServices

### ISSUE THREAD

**Issue by pakrym** [aspnet/StaticFiles#139]
DirectoryBrowser requires web encoders which are registered via `AddDirectoryBrowser` call but we don't have `AddFileServer` which would align with `UseFileServer` and the runtime error you get is hard to diagnose.

Possible solutions:
1. Add `AddFileServer` method that calls `AddDirectoryBrowser`
2. Add `DirectoryBrowserMiddleware` constructor overload which does not take `HtmlEncoder` and use default one, so it will work without any service registration.

**Comment by Tratcher** [comment]
Lets do option 2. Most of the time people don't reconfigure the encoders so the default should be fine, and if they do reconfigure it then they'll register it.
