### ISSUE TITLE
Inconsistent handling of multiple slashes in path

### ISSUE THREAD

**Issue by mikeharder** [aspnet/StaticFiles#147]
StaticFiles is inconsistent with handling of multiple slashes in a path.  It appears to be allowed inside a path, but not at the start.

```
http://host/foo/bar.html  -> 200

http://host//foo/bar.html -> 404

http://host/foo//bar.html -> 200
```

It should be either allowed or disallowed in all parts of the path.

**Comment by Tratcher** [comment]
Is this actually caused by static files logic, or is it physical file provider? Embedded file provider will be different.

**Comment by muratg** [comment]
@JunTaoLuo Could you investigate?

**Comment by JunTaoLuo** [comment]
Our checks for rooted paths in the physical file provider is preventing the request from being resolved. https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.Extensions.FileProviders.Physical/PhysicalFileProvider.cs#L201
If we encounter a path that begins with a forward slash, we strip the first slash. However, if you have two, we only strip the first one and the rest is interpreted as an absolute path which we do not allow for security reasons. Maybe we can trim all leading forward slashes? Is there a reason we are not doing that?

**Comment by muratg** [comment]
@JunTaoLuo I think that's a good idea. Would that break anything that you can think of?

**Comment by JunTaoLuo** [comment]
I can't think of any breaks that would be caused by trimming multiple leading slashes. Any concerns @Tratcher? Security especially?

**Comment by Tratcher** [comment]
Try it with the StaticFiles tests. Also try it on unix.
@blowdart?

**Comment by JunTaoLuo** [comment]
Tests run fine and I've tested with the static files on core, full framework and core on osx.

**Comment by blowdart** [comment]
What about trying to escape out of the static file root?
