### ISSUE TITLE
Allow handling the response when the file is not found

### ISSUE THREAD

**Issue by mrahhal** [aspnet/StaticFiles#155]
Currently if the file is not found the middleware will call `next` anyway. It might be desirable to short circuit at this point and just return a 404.

Now, this can be done by using an "app" middleware right after using the `StaticFiles` one, but it will need to try and match the `RequestPath` against what the `StaticFiles` middleware is configured to handle. This doesn't look cool at all.

### Suggestion:

Add:
```cs
public Func<StaticFileNotFoundContext, bool> OnFileNotFound { get; set; }
```
to `StaticFileOptions`. The return value of invoking `OnFileNotFound` might be used to tell `StaticFiles` that the request has been handled and thus shouldn't call next.

If this sounds good, I'd be happy to make a PR.

**Comment by Tratcher** [comment]
I don't recommend doing this, it would provide the same functionality as having your own middleware next in the pipeline. Note the event would fire for every MVC page / API, you'd have lots of noise.

**Comment by mrahhal** [comment]
Ok, here's the issue. I'm using angular, and because of that I have to do a "catch all" route in mvc so that angular can handle 404s on the client. The problem isn't with angular, if you're using any spa framework that has its own routing system you're forced to do that. The result? If I request a static file the response will be an html webpage.

Also, the event won't fire for every route because of `fileContext.ValidatePath` [here](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L78). This method already checks for a match (if the url starts with the expected segment) before looking up whether the file exists or not. And as such, `OnFileNotFound` would only be called [here](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L88).

**Comment by Tratcher** [comment]
A different approach I've seen for angular is to use UrlRewrite: https://github.com/aspnet/BasicMiddleware/issues/43

Note that fileContext.ValidatePath is empty most of the time, static files are served from the root url.

**Comment by mrahhal** [comment]
Ah, missed that StaticFiles would handle things in the root in a default setup. I'll check that approach. Thanks!
