### ISSUE TITLE
IHostingEnvironment.WebRootFileProvider, script tag helper, and static files middleware.

### ISSUE THREAD

**Issue by dazinator** [aspnet/StaticFiles#158]
Suppose you use static files, with your own file provider like so:

```
          var specialFilesProvider= new PhysicalFileProvider("C:\\SomeFolder\\wwwroot");
          PathString requestPath = new PathString("/specialfiles");

            var staticFileOptions = new StaticFileOptions()
            {
                FileProvider = specialFilesProvider,
                RequestPath = requestPath
            };         
            appBuilder.UseStaticFiles(staticFileOptions);
```

Now, on the client / browser, you can now request a file like so:

"http://your-website.com/specialfiles/yourFile.js"

The static files middleware, will map the request path: `/specialfiles` to the file provider specified. It then removes the request path '/specialFiles' from the file path when requesting the file via the File Provider. So in other words, the FileProvider sees a request for the file 'yourFile.js`

This works fine, but the problem comes when you try and use some standard MVC features which resolve files using the `IHostingEnvironment.WebRootFileProvider` such as the script `TagHelper`.

Place this in a View:

```
<script asp-src-include="/specialfiles/**/*.js"></script>
```

This is using the standard MVC tag helper. The problem is, the TagHelper will check to see if files exists, using the IHostingEnvironment's webroot file provider. StaticFiles does not seem to integrate with that, which means that MVC can't see the files, so nothing is output on the page.

I thought to work around this by manually adding the FileProvider to the IHostingEnvironment.WebRootFileProvider (as a composite file provider) but the problem there is that the file provider doesn't know anything about the RequestPath. In other words if you do that, then this will then work (note the request path is removed)

```
<script asp-src-include="/**/*.js"></script>
```

but this will still not work:

```
<script asp-src-include="/specialfiles/**/*.js"></script>
```

Please can StaticFiles hook the IHostingEnvironment.WebRootFileProvider appropriately so that other MVC features can resolve files set up to be served on request paths appropriately.

**Comment by Tratcher** [comment]
Hosting configures StaticFiles, not the other way around. That said, the various components are making a few assumptions that don't hold for your scenario.

The script tag helper assumes that the WebRootFileProvider's url path is the site root. @NTaylorMullen any way to adjust that?

Some possible workarounds:

Does your site have any static files not under the url `/specialfiles/`? This layout does seem uncommon. This should work if you put your files into a physical directory `\specialfiles\` and didn't set StaticFileOptions.RequestPath.

You can also add multiple static file providers with different physical paths and url paths.

**Comment by dazinator** [comment]
> Does your site have any static files not under the url /specialfiles/? This layout does seem uncommon. 

Yes it does. I am using a CompositeFileProvider on the Environment web root file provider, in order to resolve static files from multiple locations.

> This should work if you put your files into a physical directory \specialfiles\ and didn't set StaticFileOptions.RequestPath.

The files come from an external location, not nested within the website folder, so I can't move them within a project subfolder.

> You can also add multiple static file providers with different physical paths and url paths.

Yeah, but they don't integrate with the MVC script tag helper which is kind of my issue.

In order to get this to work, it seems what I would need to do, is create my own `IFileProvider` that can accept a "RequestPath" in its contructor. Then add this to the HostingEnvironments WebRootFileProvider (Composite). That way when the script tag helper tries to get the script file from the webroot file provider, my file provider will intercept that request, remove the "RequestPath" from the file subpath, and then resolve the file.

I'm surprised no one has encountered this yet.. because you would hit this whenever using script tag helper, and static files middleware with a "request path" set.

**Comment by Tratcher** [comment]
Adding an IFileProvider that handles RequestPath seems like a good solution to your problem. This could be a generic wrapper around another IFileProvider so you wouldn't have to re-implement the functionality across providers. Let us know what you come up with and we may consider it for the FileSystem repo.

I don't anticipate making any changes to StaticFiles for this. StaticFiles does not create its file providers, it takes them from IHostingEnvironment or from Options.

Are there any other features that use WebRootFileProvider? These are the ones I can find:
- Url Rewrite 
- VirtualFileResultExecutor
- ImageTagHelper
- ScriptTagHelper
- LinkTagHelper

**Comment by dazinator** [comment]
Ok sounds good to me.
Interestingly.. by creating a FileProvider that handles request path and delegates to an underlying FileProvider, by adding this to IHostingEnvironemebnt.WebRootFileProvider, there should then be no need to configure static files middleware options with IFileProvider / request paths at all.. as the WebRootFileProvider can handle everything.. I'll give this a try

**Comment by dazinator** [comment]
Ok I have created a basic `RequestPathFileProvider` here: 
https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders

**Comment by Tratcher** [comment]
Nice.
Careful with StartsWith if you want to limit to full segment matches. Currently `/dir` will match `/dir/foo` (returns `/foo`) and `/dirfoo` (returns `foo`). PathString has some good helper methods for StartsWithSegment you can check.

**Comment by dazinator** [comment]
Thank you. Excellent - I was hoping the framework would have something better for this, I will check out PathString!

**Comment by Cubelaster** [comment]
In my case, I was missing the 

```
    <handlers>
        <add name="AspNetStaticFileHandler" path="*" verb="*" type="System.Web.StaticFileHandler" />
    </handlers>
```

In system.webServer part of my web.config.
Adding that made all the script and the rest of tags to work ok.
