### ISSUE TITLE
High number of static files cause debugger crash and dotnet hang

### ISSUE THREAD

**Issue by steveoh** [aspnet/StaticFiles#160]
#### Did you read the documentation? 
Yes

#### Did you include the snippet of broken code in the issue?
```cs
var myProvider = new FileExtensionContentTypeProvider();
myProvider.Mappings.Add(".glsl", "text/plain");

app.UseStaticFiles(new StaticFileOptions {
  ContentTypeProvider = myProvider
});
```
#### What are the EXACT steps to reproduce this problem?
I am writing an app that using the esri javascript api which is built on top of dojo. This is important since dojo embraces the AMD module syntax and in development a lot of modules get requested. This particular project makes around 700 requests for loading a slippy map. This takes about 20-30 seconds which is another issue but occasionally the dotnet process hangs and `ERROR: CLRDBG exited unexpectedly with exit code 139 (0x8B). Debugging will now abort.` is thrown from vs code. The requests sit in a `pending` state in the chrome dev tools and the tab cannot be closed. `pgrep 'dotnet' | xargs kill` is the only way to start up another debug session.

#### What package versions are you using (you can see these in the project.json file)?
[project.json](https://gist.github.com/steveoh/113087341e592ea9575ea4fe177abf42)

#### What operating system are you using?
OSX Sierra

#### What version of IIS are you using?
none at the moment

**Comment by Tratcher** [comment]
Do you also experience the dotnet hang without the debugger attached? Or is it only with the debugger?

(Your gist link doesn't work)

**Comment by steveoh** [comment]
I updated my project.json gist. I'll try running without the debugger attached a few times today.

**Comment by steveoh** [comment]
@Tratcher no I have not been able to make it happen without the debugger. It seems to only be with the debugger. It's waaaay faster without the debugger attached for sending the static files also.

**Comment by Tratcher** [comment]
Maybe you need to add some sleeps to slow it down for a repro :-)

**Comment by muratg** [comment]
@steveoh Please let us know if you're still hitting issues (file a new bug). Closing this one.
