### ISSUE TITLE
ChangeTokens and signalling Deleted files

### ISSUE THREAD

**Issue by dazinator** [aspnet/StaticFiles#162]
Hello,

In my custom IFileProvider, i'd like it to behave correctly when a file being watched is deleted. I already have it returning a custom `IChangeToken` for the watched file, but i'm not clear on exactly what needs to be done in order to correctly signal a Delete. Are there any examples of this that I could look at? Is it just as simple as passing `Null` when raising the callbacks - i.e:

```
                     myChangeToken .HasChanged = true;
                    myChangeToken.RaiseCallback(null);

```

Where all `RaiseCallback` does is loop through the subscribed listners and invoke them passing the specified argument - which usually would be the updated file, but in this case as the file is deleted, I guess I would need to set it to null?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/FileSystem#241

**Comment by dazinator** [comment]
oops sorry wrong repo! That will teach me to have too many github pages open at once.
