### ISSUE TITLE
Pre-Condition Bug for IfUnModifiedSince

### ISSUE THREAD

**Issue by dougkpowers** [aspnet/StaticFiles#166]
I believe there is a bug in the ComptueIfModifiedSince() method of the StaticFileContext class.  The following line (213) reads:
`            if (ifUnmodifiedSince.HasValue && ifModifiedSince <= now)`

but should read:
`            if (ifUnmodifiedSince.HasValue && ifUnmodifiedSince <= now)`

**Comment by Tratcher** [comment]
I think this was already fixed:
https://github.com/aspnet/StaticFiles/commit/8487bf0ae53247be8a270c2e204a7e3c46386c23

**Comment by dougkpowers** [comment]
Thx.  I was looking in master rather than dev.
