### ISSUE TITLE
DefaultFilesMiddleware doesn't work with encoded path

### ISSUE THREAD

**Issue by mifopen** [aspnet/StaticFiles#175]
Repro:
Embed the following directory structure:

    └───wwwroot
        │
        └───а
            └──index.html
where 'а' is russian letter 'а' (char)1072
Use the folowing code:

```
app.UseDefaultFiles();
```
Go to http://localhost:5000/а/ (on server it will be http://localhost:5000/%D0%B0)

Expected index.html content gets displayed
Actual: 404

**Comment by mifopen** [comment]
This happens because DefaultFilesMiddleware calls
```this._fileProvider.GetDirectoryContents(subpath.Value).Exists``` with ```subpath.Value```, but calls ```this._fileProvider.GetFileInfo(subpath + defaultFileName).Exists``` without ```subpath.Value```.
Example:
request url: http://localhost:5000/%D0%B0
context.Request.Path.ToString(): /%D0%B0
context.Request.Path.Value: /а

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2452
