### ISSUE TITLE
Allow styling/template/better look-and-feel using external css/js/html

### ISSUE THREAD

**Issue by HarelM** [aspnet/StaticFiles#176]
Hi,

I'm looking into migrating my code from .Net 4.5 WebApi to .Net Core.
This library is far better looking than the default IIS directory browser but it needs a little bit more touch to look good.
I have created for IIS the code to do it but I would rather use this library as is instead of writing my own code.
If there was a way to change the styling using the code somehow it would great as any site developer would be able to add directory browsing with the look-and-feel of his site.
If this is not possible please consider updating the current styling a bit:
You can see how it looks here:
https://israelhiking.osm.org.il/English/
The code is based on t4 template, bootstrap & font awesome and can found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Controllers/FileExplorerController.cshttps://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Controllers/FileExplorerHtmlTemplate.tt

The main differences in terms of styling are the following:
1. Table should fill width
2. Size of files should be changed according to the file size (change the units when the size is big enough - Kb, Mb, Gb).
3. Add icons for popular file types - txt, xml, zip, images folders etc.

**Comment by Tratcher** [comment]
This can be done by implementing an IDirectoryFormatter and setting it on the options.

**Comment by HarelM** [comment]
Thanks! managed to make it work. I still think the default styling should be better though (bullets 1 and 2).

**Comment by HarelM** [comment]
I have the current code up and running:
```cs
 app.UseDirectoryBrowser(new DirectoryBrowserOptions()
                {
                    FileProvider = new PhysicalFileProvider(directory.Value),
                    RequestPath = new PathString("/" + directory.Key),
                    Formatter = new BootstrapFontAwesomeDirectoryFormatter(app.ApplicationServices.GetRequiredService<IFileSystemHelper>())
                });
```
This present the file great and looks very good, but you can't download any file :-(
So I added the following code to allow downlaod:
```cs
app.UseFileServer(new FileServerOptions
                {
                    FileProvider = new PhysicalFileProvider(directory.Value),
                    RequestPath = new PathString("/" + directory.Key),
                    EnableDirectoryBrowsing = true,
                });
```
But the above code does not accept a formatter so I can't style it...
Any suggestions:
Code can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Controllers/BootstrapFontAwesomeDirectoryFormatter.cs

**Comment by HarelM** [comment]
Nevermind, found the relevant needed code (not sure if everything is needed but added it just in case):
It is weird that ```DirectoryBrowserOptions``` is read only while the rest of the proreties are not (which causes the following code not to use initialization list for all of the object)...
```cs
var fileServerOptions = new FileServerOptions
                {
                    FileProvider = new PhysicalFileProvider(directory.Value),
                    RequestPath = new PathString("/" + directory.Key),
                    EnableDirectoryBrowsing = true,
                };
                fileServerOptions.DirectoryBrowserOptions.FileProvider = new PhysicalFileProvider(directory.Value);
                fileServerOptions.DirectoryBrowserOptions.RequestPath = new PathString("/" + directory.Key);
                fileServerOptions.DirectoryBrowserOptions.Formatter = new BootstrapFontAwesomeDirectoryFormatter(app.ApplicationServices.GetRequiredService<IFileSystemHelper>());
                app.UseFileServer(fileServerOptions);
```
