### ISSUE TITLE
Authentication in OnPrepareResponse

### ISSUE THREAD

**Issue by audacity76** [aspnet/StaticFiles#181]
Hi,

I want some of my static files only accessible when I'm authenticated/logged in. Unfortunately, the user's identity inside the HttpContext of the StaticFileResponseContext isn't filled. Is there a way to enable the authentication?

**Comment by Tratcher** [comment]
OnPrepareResponse is not a good place to perform authorization. This event only lets you tweak the response before sending it, you cannot prevent the response (except by throwing).

Issue tracking this feature: https://github.com/aspnet/StaticFiles/issues/70

The best way to handle this right now is to move to an MVC controller that matches your path, checks Authorization, and sends the file. @blowdart do you have a ready example for this?

**Comment by muratg** [comment]
Closing, dup of #70

**Comment by blowdart** [comment]
Nope, it'd just be returning a FileStreamResult with the appropriate mime type though.

**Comment by audacity76** [comment]
@blowdart 

Is it a bad idea to just check if the identity cookie is set? Like

```
OnPrepareResponse = (x) =>
{
  if (!x.Context.Request.Cookies.ContainsKey(".AspNetCore.Identity.Application"))
    x.Context.Response.StatusCode = StatusCodes.Status401Unauthorized;
}
```

**Comment by Tratcher** [comment]
You can't do authorization here, the file is still sent, just with a 401 status code.

**Comment by blowdart** [comment]
And that doesn't check anything except that a cookie, any cookie has the right name. You can't do what you want using the static files middleware.

**Comment by audacity76** [comment]
Last try guys... 

@Tratcher 
Resetting Response Body and ContentLength = 0 prevents sending the file.

@blowdart 
Sure, it is only checking for the cookie existence. Is there no easy way to perform a check with identity framework with the given cookies to authenticate the user?

**Comment by blowdart** [comment]
Honestly this isn't what static files is meant for. I wouldn't try to push auth into it, you're venturing far into unsupported territory and doing that when you want security is a bad idea, and will make kittens cry.

**Comment by Tratcher** [comment]
I'll write a proper Authorized MVC Controller sample for static files when I get a chance.

**Comment by Tratcher** [comment]
It will be easier to emulate the static file middleware features in MVC after https://github.com/aspnet/Mvc/pull/6150

**Comment by lumogox** [comment]
@Tratcher Do you have an example of this?

**Comment by Tratcher** [comment]
@lumogox no, I should do that... Filed https://github.com/aspnet/AuthSamples/issues/28.

**Comment by lumogox** [comment]
@Tratcher Great!, let me know if you have a quick example that I can look. Thanks!

**Comment by Tratcher** [comment]
I'm sorry I ever recommended using MVC for this, it is not a good fit. See https://github.com/aspnet/Home/issues/2457#issuecomment-383186581 for discussion and an alternate sample using middleware and pipeline branching.
