### ISSUE TITLE
Configuring the file hierarchy in a module/feature based application

### ISSUE THREAD

**Issue by mariuszkochanowski** [aspnet/StaticFiles#183]
What should i do if i want to create module/feature based application that is organized like below:
```
/Features
	/Feature1
		/Controllers
			/ControllerA.cs
		/Views
			/View1OfControllerA.cshtml
		/Scripts
			Script1.js
			...
		/css
			css1.css
			...
	...
	and many other features
```
I have managed view localization with custom DynamicViewLocationExpander that creates view locations based on namespace of controller, but now i am stuck with configuration of static files.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2451
