### ISSUE TITLE
Headers configuration file

### ISSUE THREAD

**Issue by sebastienros** [aspnet/StaticFiles#188]
Like it was done in System.Web I'd like to be able to set default headers like `max-age` per folder.
The first thing I want to do when serving static file is define this header.

An implementation could look for a specific file in the folder the file is served, using the same `FileProvider` as the options. This can already be done using code by altering the `Response` but configuration is better in this case IMO.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2448
