### ISSUE TITLE
Return a single range instead of a collection from ParseRange

### ISSUE THREAD

**Issue by jbagga** [aspnet/StaticFiles#196]
[ParseRange](https://github.com/aspnet/StaticFiles/blob/dev/shared/Microsoft.AspNetCore.RangeHelper.Sources/RangeHelper.cs#L27) should return a single `RangeItemHeaderValue` (multiple are not supported) instead of `ICollection<RangeItemHeaderValue>`
As a follow up, the caller code in StaticFileContext and FileResultExecutorBase in MVC should be modified.

cc @Tratcher

**Comment by Tratcher** [comment]
And you can probably combine it with NormalizeRanges.
