### ISSUE TITLE
Replace Constants.CompletedTask and its usages with Task.CompletedTask

### ISSUE THREAD

**Issue by EvanMulawski** [aspnet/StaticFiles#201]
See [Constants.cs, L20-27](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/Constants.cs#L20).

Now that `Task.CompletedTask` is available, there is no need to create a custom one.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2447
