### ISSUE TITLE
HTTP Header Range not working on macOS Sierra

### ISSUE THREAD

**Issue by sunary** [aspnet/StaticFiles#207]
I'm using *FileStreamResult* to stream video in **dotnet core 2.0.0-preview2-006497**
With window 10 and ubuntu, I can seek video but It doesn't work on macOS Sierra.

**Comment by Tratcher** [comment]
@jbagga

**Comment by jbagga** [comment]
@sunary Are you able to provide a sample app that is running in to this issue? Which browser are you using?

**Comment by sunary** [comment]
This is my sample app:
```csharp
var filePath = "sample.mp4";
FileStream file = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, 8 * 1024 * 1024);
return new FileStreamResult(file, "video/mp4");
```
I check it on **chrome Version 59.0.3071.115** only

**Comment by jbagga** [comment]
@sunary I used the following [sample app](https://github.com/jbagga/StreamVideo) and was unable to repro on macOS Sierra 10.12.4. Can you provide more details? Feel free to modify my sample.

**Comment by jbagga** [comment]
@sunary Closing for now as it cannot be reproduced. Feel free to reopen with more details if you are still seeing the issue!

**Comment by sunary** [comment]
Sorry, your project using **ASP.NET Core 2.0 Preview** and its not working on my mac.

**Comment by sunary** [comment]
Its worked after completely remove dotnet version 1.0.4. Thanks for your support

**Comment by jbagga** [comment]
You can add a global.json file specifying the version you want to use to your solution directory
` { "sdk": { "version": "2.0.0-preview2-006497" } }`

You shouldn't have to delete the older SDKs.
