### ISSUE TITLE
Missing .msg mimetype mapping

### ISSUE THREAD

**Issue by dviry** [aspnet/StaticFiles#211]
StaticFiles/src/Microsoft.AspNet.StaticFiles/FileExtensionContentTypeProvider.cs

Is missing the Outlook .msg mimetype - currently manually doing the following:

var provider = new FileExtensionContentTypeProvider();
provider.Mappings.Add(".msg", "application/vnd.ms-outlook");

... but I think it would be good to have it included directly in the code.

**Comment by muratg** [comment]
I don't think we'll be doing this, and the code to manually add the mimetype is pretty straightforward. 

cc @Tratcher
