### ISSUE TITLE
How to use pregzipped js files in angular

### ISSUE THREAD

**Issue by akashshelke22** [aspnet/StaticFiles#216]
I have an angular application. I am using webpack and commonjs. i have minified all js files. Now i have **vendor.js**(angular lib file) of size 888 kb and **vendor.js.gz** 195 kb. 
But i don't know how to use this **vendor.js.gz** file. 

I also tried to enable compression from iis but no luck. It shows me 'transferred- encoding': chunked in response header instead of 'content-encoding': gzip.

So, please help me if anyone knows gzip implementation

**Comment by Tratcher** [comment]
This isn't supported. We've done some research on it recently but it looks like it will take some invasive changes in the stack to make it work. We're stuck with dynamic compression for now.

Are you primarily trying to do this to reduce:
A) Deployment size?
B) CPU utilization?
C) Download size?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2444
