### ISSUE TITLE
StaticFileContext.ValidateMethod wrongly named

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/StaticFiles#217]
The `ValidateMethod` in the `StaticFileContext` should probably be named `IsValidMethod`.

**Comment by Tratcher** [comment]
I don't see why. It's doing more work than the IsXXX properties.

**Comment by vanillajonathan** [comment]
It does not really do any action, it just checks conditions.

It checks if something **is** valid by checking if the HTTP request method **is** a GET or a HEAD.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2443
