### ISSUE TITLE
Add support for .webmanifest file extension

### ISSUE THREAD

**Issue by madskristensen** [aspnet/StaticFiles#219]
This is used in Progressive Web Apps (PWAs) for the manifest JSON file. 

The content type should be `application/manifest+json`

**Comment by muratg** [comment]
cc @glennc

**Comment by Tratcher** [comment]
Is there a spec reference?

**Comment by madskristensen** [comment]
<https://w3c.github.io/manifest/#media-type-registration> shows the content type `application/manifest+json` and a little further down in the same chapter the `.webmanifest` file extension.

Sorry, I should have added this when I opened the bug

**Comment by RehanSaeed** [comment]
Just saw this issue, I already raised https://github.com/aspnet/StaticFiles/pull/221 to fix this.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2442
