### ISSUE TITLE
Is this unecessary if you are referencing IIS

### ISSUE THREAD

**Issue by bdelaney** [aspnet/StaticFiles#26]
In a vNext project, do you need this referenced when you already have Microsoft.AspNet.Server.IIS referenced in project.json?

**Comment by Tratcher** [comment]
This package is primarily for use outside of IIS. When running in IIS you can choose to use either the native module or this package. Note you need to enable RAMFAR to use this package in IIS.

**Comment by Eilon** [comment]
Indeed, each has slightly different functionality so even in IIS you might want to use the StaticFiles middleware.

**Comment by borgdylan** [comment]
This middleware should be included always if you want to have an app that can be hosted on any ASP.NET 5 compatible server. It will do no harm to have it on IIS

**Comment by Eilon** [comment]
@borgdylan yup that's why I do in most of my web projects.

**Comment by Praburaj** [comment]
Closing this as question seems to be answered.
