### ISSUE TITLE
Prefer the new encoders over the old WebUtility APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/StaticFiles#29]
There are still some call sites in the StaticFiles code base that invoke WebUtility.HtmlEncode.  These call sites should instead use IHtmlEncoder.HtmlEncoder.

**Comment by Praburaj** [comment]
How should I get this service from static files. Can I instantiate an object of type `HtmlEncode`?

**Comment by GrabYourPitchforks** [comment]
You'll be able to pull an instance of IHtmlEncoder from the DI framework.  We're still figuring out who is responsible for registering these instances in the first place. :)

**Comment by GrabYourPitchforks** [comment]
The types `IHtmlEncoder`, `IJavaScriptStringEncoder`, and `IUrlEncoder` are in the Microsoft.AspNet.WebUtilities package. To register them from within your own AddServices method, reference the Microsoft.AspNet.Http.Extensions package and call `AddEncoders`.
