### ISSUE TITLE
application/font-woff2 not working when using Asp.Net VNext

### ISSUE THREAD

**Issue by AustinFelipe** [aspnet/StaticFiles#34]
I'm doing some experiments with VNext + OSX + Chrome. I'm trying to get a woff2 file

    GET http://localhost:5003/fonts/fontawesome-webfont.woff2?v=4.3.0 

But an error occur. See the request's header below

    Remote Address:127.0.0.1:5003
    Request URL:http://localhost:5003/fonts/fontawesome-webfont.woff2?v=4.3.0
    Request Method:GET
    Status Code:404 Not Found

This is my Startup.cs

    public void Configure(IApplicationBuilder app)
    {
        app.UseStaticFiles();

        app.UseServices(services =>
        {
            services.AddMvc();
        });

        // Add MVC to the request pipeline
        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller}/{action}/{id?}",
                defaults: new { controller = "Home", action = "Index" });
        });
    }

It seems to be supported in the class below.

https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/FileExtensionContentTypeProvider.cs

Can you guys give me some help?

**Comment by Eilon** [comment]
Which package version of StaticFiles are you using? This change is only in the newest builds, it wasn't in beta3. It's in beta4 builds only.

**Comment by AustinFelipe** [comment]
Oh, I'm using the beta3. Installing via homebrew it seems to be the lastest version.
