### ISSUE TITLE
Serving of files is broken

### ISSUE THREAD

**Issue by borgdylan** [aspnet/StaticFiles#35]
Since the HTML encoders enablement, serving of HTML, images etc. has been broken.  Only javascript is being served. Are encoders being demanded even when none are desired?

**Comment by borgdylan** [comment]
The middleware is returning 206 Partial Content instead of the usual 200 OK.

**Comment by Eilon** [comment]
Can you clarify what's broken?

**Comment by borgdylan** [comment]
I seem to only manage to serve JS files.

**Comment by Eilon** [comment]
Which server are you using? (Kestrel, IIS, WebListener, etc.) Anything else interesting about the app? I want to make sure we have enough info to try to reproduce the issue.

**Comment by borgdylan** [comment]
I am using Nowin on Mono.
