### ISSUE TITLE
StaticFiles is broken on OWIN servers

### ISSUE THREAD

**Issue by borgdylan** [aspnet/StaticFiles#36]
After checking with the Hosting repo which fixed OWIN in general, serving of static files is still broken. MVC works OK.

**Comment by Praburaj** [comment]
@borgdylan I tried static file middleware and MVC with the Entropy sample - with Nowin (server factory is in the same project as the app) as well as moved the serverfactory to a different project and tried that as well. I can't reproduce the static file issue. Can you try again with latest bits?

**Comment by Praburaj** [comment]
No - repro. @borgdylan If you could still reproduce feel free to reopen the issue.
