### ISSUE TITLE
Should UseSendFileFallback IApplicationBuilder extension live in Microsoft.AspNet.Builder like all other extensions

### ISSUE THREAD

**Issue by Praburaj** [aspnet/StaticFiles#43]
https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/SendFileExtensions.cs#L20

This probably is the only IApplicationBuilder extension in our code base living in a different namespace.

**Comment by muratg** [comment]
Yes, folks shouldn't have to add a using statement to use the extensions. 

/cc @glennc

**Comment by Tratcher** [comment]
This was intentional. This is a piece of infrastructure that will rarely be used directly by app developers.

We've used this approach elsewhere too, its not unique.

Sent from my Windows Phone
________________________________

**Comment by Praburaj** [comment]
@Tratcher sounds good.
