### ISSUE TITLE
StaticFiles not returning modified files

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/StaticFiles#52]
Updated to latest from the nighties today and only unchanged files were getting 304.  modified files were getting 404.

**Comment by matthewDDennis** [comment]
To clarify, I've debugged with the staticFiles src, and found that in StaticFileContext.LookupFileInfo, when _subPath.Value = "/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css", which does exist, the call to
fileInfo = _options.FileProvider.GetFileInfo(_subPath.Value);
results in fileInfo.Exists == false;

**Comment by matthewDDennis** [comment]
Renaming the /lib/bootstrap and /lib/bootstrap-touch-carousel directories to bootstrap and bootstrap-carousel fixed the issue.  Maybe grunt mangled the names when it copied the files?  I couldn't see any funny characters.

**Comment by matthewDDennis** [comment]
Just a not, these were the only copied directories that had /dist/**/ in the copy instructions.
```js
/// <binding Clean='clean' />

var gulp = require("gulp"),
	rimraf = require("rimraf"),
	fs = require("fs");

eval("var project = " + fs.readFileSync("./project.json"));

var paths = {
	bower: "./bower_components/",
	lib: "./" + project.webroot + "/lib/"
};

gulp.task("clean", function (cb) {
	rimraf(paths.lib, cb);
});

gulp.task("copy", ["clean"], function () {
	var bower = {
		"angular": "angular/angular*.{js,map}",
		"boostrap": "bootstrap/dist/**/*.{js,map,css,ttf,svg,woff,eot}",
		"boostrap-touch-carousel": "bootstrap-touch-carousel/dist/**/*.{js,css}",
		"hammer.js": "hammer.js/hammer*.{js,map}",
		"jquery": "jquery/jquery*.{js,map}",
		"jquery-validation": "jquery-validation/jquery.validate.js",
		"jquery-validation-unobtrusive": "jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"
	};

	for (var destinationDir in bower) {
		gulp.src(paths.bower + bower[destinationDir])
			.pipe(gulp.dest(paths.lib + destinationDir));
	}
});
```

**Comment by muratg** [comment]
What server are you using?  

cc @Tratcher

**Comment by muratg** [comment]
I assume you're using Helios and IIS.  Putting this in the Backlog.
