### ISSUE TITLE
More overloads for UseStaticFiles

### ISSUE THREAD

**Issue by Tratcher** [aspnet/StaticFiles#57]
There are currently only two convenience overload for UseStaticFiles, one with no params for the base request path and wwwroot folder, and one that lets you set alternate requests paths to map to wwwroot. 

We need at least one more overload that lets you select a file path (relative to wwwroot) that maps to the base request path. An additional overload that let you set both the request path and the file path would be nice.

Here's what we currently have to do to select an alternate file path:

``` c#
app.UseStaticFiles(new StaticFileOptions() { FileProvider = new PhysicalFileProvider(Path.Combine(hostingEnv.WebRootPath, "./src/client/"))  });
```

**Comment by jskulavik** [comment]
This is a critical enhancement IMHO.  As it stands today, I cannot host static files in ASPNET5 can I?  Please advise; do I need middleware to host static files?

@Tratcher: In your above snippet, where does "hostingEnv" come from?  Would that snippet work?  Absolute paths with PhysicalFileProvider do not work and throws System.IO.DirectoryNotFoundException.

**Comment by Tratcher** [comment]
IHostingEnvironment: https://github.com/aspnet/Docs/blob/dev/aspnet/contribute/style-guide/_static/startup.cs

**Comment by jskulavik** [comment]
My goodness @Tratcher, that's the most simple and beautiful resolution.  Thank you very much.

**Comment by muratg** [comment]
@Tratcher What would the signature be for the overload?  Note that we already have this:

``` public static IApplicationBuilder UseStaticFiles(this IApplicationBuilder app, string requestPath)```

**Comment by Tratcher** [comment]
Something like `public static IApplicationBuilder UseStaticFiles(this IApplicationBuilder app, string requestPath, string physicalPath)`.

**Comment by muratg** [comment]
@Tratcher RC2?

**Comment by Tratcher** [comment]
Non-critical, backlog until we get additional feedback.

**Comment by VanCoding** [comment]
I also need this. @Tratcher 's suggested overload looks good.

What would've been even better:
`public static IApplicationBuilder UseStaticFiles(this IApplicationBuilder app, string physicalPath)`

Because `requestPath` can be set more transparently using
```
app.Map("/public",fileapp=>{
    app.UseStaticFiles("c:/publicFiles/");
});
```
But that would clash with the current method, so that's not possible anymore.
