### ISSUE TITLE
StaticFiles 404 after time elapsed

### ISSUE THREAD

**Issue by vbnewb** [aspnet/StaticFiles#59]
Team,
I've been using beta4 and everything appears to work great initially but after some time (ie 2 hours of testing with users) the static files (js files mostly) start returning 404 this continues until i restart the app pool.

So far I've seen nothing being logged except the 404 in IIS and from .NET using logging middleware for Information level or above.

**EDIT**
Read that StaticFiles middleware may not be getting used while running on IIS. If this is the case the issue may not be related to this project. Will provide an update when root cause is determined.

**Comment by Tratcher** [comment]
This isn't actionable without a repro. Can you work out a repro app and commit it to github?

**Comment by vbnewb** [comment]
I have not tracked down the issue yet but it exists even when not using StaticFiles. I will close the issue.
