### ISSUE TITLE
Added/Updated MIME Types

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/StaticFiles#63]
Added the following MIME types which I have found to be missing:

- .json - application/json (This one is pretty unbelievable)
- .ttc - application/x-font-ttf
- .webp - image/webp
- .appcache - text/cache-manifest
- .manifest - text/cache-manifest

Also the following MIME types need updating:

- .ttf should be application/x-font-ttf and not application/octet-stream

I've created a new Pull Request https://github.com/aspnet/StaticFiles/compare/dev...RehanSaeed:patch-1

**Comment by muratg** [comment]
@RehanSaeed Could you create a GH pull request (based on your check-in) so that we can put code review comments?  Thanks.

**Comment by RehanSaeed** [comment]
@muratg Here you go https://github.com/RehanSaeed/StaticFiles/commit/545fa9e70a8308097554dc56ed0e82feb309bb34
