### ISSUE TITLE
Always use UTC time

### ISSUE THREAD

**Issue by Tratcher** [aspnet/StaticFiles#66]
Ported from: http://katanaproject.codeplex.com/SourceControl/network/forks/uecasm/LastModified/contribution/8369#!/tab/changes

https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/StaticFileContext.cs#L137

LastModified from the file info might be in local time. We should convert it to UTC before attempting any comparisons.

The switch to strongly typed headers at least fixed the header value output: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L239

**Comment by uecasm** [comment]
The timezone offset of `_lastModified` is retained, so in theory it should do comparisons correctly regardless of whether they're local or universal.  Though it wouldn't hurt to confirm that as I haven't used `DateTimeOffset` much myself.

**Comment by muratg** [comment]
@Tratcher Are we doing this in RC2?

**Comment by Tratcher** [comment]
Yes, we should do it.

**Comment by BrennanConroy** [comment]
e05469a989075aef1eeba83f1fba4125d054fd90
