### ISSUE TITLE
Add/Update logging in static files middleware

### ISSUE THREAD

**Issue by rynowak** [aspnet/StaticFiles#69]
From offline logging discussion:

Add Verbose logging where it can be useful for debugging
- Time box to 2 dev-days maximum (across all of k-core)
- Use EventIds at each logging statement
- Update any existing logging to include an EventId

Relevant logging points we want to include for sure:

```
        - Served a file - Information
        - Did not serve a file
```

**Comment by muratg** [comment]
@Tratcher Looks like a good suggestion. Want to take a stab at very early RC1?

**Comment by Tratcher** [comment]
`Did not serve a file` would fire for almost every request, sounds like it should be verbose or debug.  @rynowak Any examples of work already done that uses EventIds?

**Comment by rynowak** [comment]
Yes, not-serving a file would be Verbose.
