### ISSUE TITLE
Add Windows specific tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/StaticFiles#72]
https://github.com/aspnet/StaticFiles/pull/71#issuecomment-144259485
The tests were cleaned up to run on Linux/mac/travis, but we're no longer testing some Windows specific behaviors.
- `\` vs `/`
- Case insisitivity

**Comment by muratg** [comment]
We'll finish in RC2

**Comment by BrennanConroy** [comment]
0708c3433127db527b6160bbda11a047499ac9e9
