### ISSUE TITLE
CSS/JS files returning 404 on site published on azure in a virtual directory

### ISSUE THREAD

**Issue by Junicus** [aspnet/StaticFiles#73]
I have a site generated from the default template where I edited the site.css provided and added some extra js files.  When I publish to azure as a root website it works perfect, now I need to publish to a different site but as a virtual directory.

I configured the virtual directory in the azure portal and changed the publishing profile to include the site name and url destination like so:

in Azure

virtual directory: /dashboard
physical path: site/dashboard
application: checked

and in the publishing profile

site name: <mysite>/dashboard
destination url: http://<mysite>.azurewebsites.net/dashboard

When published I can see the files in the correct physical path but when the site loads the files in css and js return 404 so the app is not working correctly.  I'm looking for the files at http://<mysite>.azurewebsites.net/dashboard/css/site.css

I don't know if somebody can duplicate the behavior, and can help me figure out the workaround, I assumed it's in the StaticFiles middleware because if I'm not mistaken those files get served by it.

**Comment by Junicus** [comment]
Checked the detailed log of the azure site and the error says that StaticFile is indeed the one setting the 404 code.  It is looking at the physical path D:\home\site\dashboard\js\site.js in the log that I looked at.
Don't know if this is the correct full path for an azure website, anybody with more experience in this can confirm that the path is normal for an azure website.

**Comment by Tratcher** [comment]
The static file middleware never sets 404 status codes. What you're seeing in the log is probably the IIS static file native module. It is often short circuits requests that resemble static files before they reach asp.net. You can work around this by adding the following to your web.config:
```
<configuration>
   <system.webServer>
      <modules runAllManagedModulesForAllRequests="true" />
   </system.webServer>
</configuration>
```

FYI: This shouldn't be needed anymore after we release beta8 due to changes in our IIS hosting.

**Comment by muratg** [comment]
Per [the changes in our IIS hosting strategy](https://github.com/aspnet/Announcements/issues/69), this wouldn't be a problem after Beta 8 ships.  In the meantime, please use the workaround @Tratcher  suggested, and if it doesn't fix your problem let us know.  Thanks.

**Comment by Junicus** [comment]
I made the change you suggested to the web.config, and published the site again.  Turned on logs again and the same error is still showing.  

You were right it's the IIS log, it's the html page and I was opening it in Code.  It tripped me that it said Module ManagedPipelineHandler and the handler is StaticFile.  Can't be sure if the physical path is right, since I don't know if I could even get full access to the azure site instance :) looking at the ftp path is not the same.

The change to the web.config didn't seem to have any results.

Any other suggestions that could help, would be awesome, but if not I can wait until beta8 to try again.

**Comment by Tratcher** [comment]
The vdir may be throwing off your site layout. The vdir should only change your url, your underlying file layout should remain the same.

Layout:
vdir: /dashboard
vdir target: site/wwwroot
app root: site/approot
static files: site/wwwroot
web.config: site/wwwroot/web.config
css: site/wwwroot/css/site.css
etc..

**Comment by Junicus** [comment]
I get that and it would be fine if there wasn't another app in wwwroot, in this case it's an installation of WordPress from the azure gallery, so I can't use wwwroot for the vdir target.  Unless I change the path for the WordPress site but that is live and it would be very unfortunate if the site went down because I mucked about in that part of it.

I think I have a solution to my problem, but want to confirm that this could be where it's getting confused.  In the project.json of the published site the path for webroot is pointing to ../../../wwwroot.

Is this where StaticFiles gets the path to look for the files to serv?, and if so, maybe I will need to change that to fix my issue.  Will try that and report progress.

**Comment by Junicus** [comment]
The issue was indeed the webroot path set in project.json.  I edited the published file and it fixed the 404 issue.
