### ISSUE TITLE
PhysicalFileProvider could use a Credentials option.

### ISSUE THREAD

**Issue by jovnas** [aspnet/StaticFiles#77]
(In Startup.cs)

    app.UseFileServer(new FileServerOptions
    {
        RequestPath = new PathString("/webpath"),
        FileProvider = new PhysicalFileProvider(@"\\other.server\share\subfolder"),
        EnableDirectoryBrowsing = false
    });

This only works if the application is running as a user with access to the share.
I believe that passing specific credentials into the PhysicalFileProvider would be the most straight forward approach. (For example, if you have to map multiple shares on different servers with different user credentials.)

(If I've missed something, please point me in the right direction and scratch this issue... :-) )

**Comment by muratg** [comment]
@jovnas Should this be filed in FileSystem repo instead?

**Comment by jovnas** [comment]
Oops! My bad.
Since StaticFiles was the feature that was affected, I just assumed it belonged here.
Will add the issue to FileSystem instead.
