### ISSUE TITLE
Logging: Suggest silencing normal operations at `LogLevel.Information`

### ISSUE THREAD

**Issue by dougbu** [aspnet/StaticFiles#79]
Current output from this repo does not add much over that from Hosting at `LogLevel.Information`. Appears even more redundant with scopes included. Suggest moving output about non-events like an unmodified file to `LogLevel.Verbose`.

An example from RC1's MusicStore app with info messages enabled:

```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      => RequestId:0HKNB5219GSUA RequestPath:/Content/Site.css
      Request starting HTTP/1.1 GET http://localhost:5000/Content/Site.css
info: Microsoft.AspNet.StaticFiles.StaticFileMiddleware[6]
      => RequestId:0HKNB5219GSUA RequestPath:/Content/Site.css
      The file /Content/Site.css was not modified
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      => RequestId:0HKNB5219GSUA RequestPath:/Content/Site.css
      Request finished in 0.0015ms 304 text/css
```

**Comment by muratg** [comment]
@dougbu if you have some time to do this, please feel free to send a PR. :)

**Comment by dougbu** [comment]
:ok: sounds like some quick weekend fun

**Comment by Tratcher** [comment]
These levels were already reviewed and explicitly selected. /cc: @rynowak @lodejard 

In theory each middleware should log one or more messages in the event that they handle the request.
