### ISSUE TITLE
Static Files and Cors

### ISSUE THREAD

**Issue by Fosol** [aspnet/StaticFiles#80]
I'd like to add CORS header values to static files.  Anyone want to point me in the right direction?  I don't seem to be able to app.UseCors().

**Comment by Eilon** [comment]
@kichalla any thoughts on this?

**Comment by kichalla** [comment]
@Fosol Can you share what your scenario is where you need this? Normally GET requests to static files for example, when a html page is being rendered(let's say at origin A) and the images are being pulled from other origin(let's say origin B)) , the scenario should just work fine without origin B doing anything related to Cors...this would work as these GET requests are classified as `Simple requests`

**Comment by Fosol** [comment]
Technically I don't need CORS headers for static files.  We were having XSS issues but I found out it wasn't related to static files.

I would like to add headers to static files.  So far I haven't been able to do this.

**Comment by kichalla** [comment]
I see that you have figured out how to add headers to the response...closing this issue now...
https://github.com/aspnet/HttpAbstractions/issues/483

**Comment by Fosol** [comment]
Thanks!
