### ISSUE TITLE
Serve index.html by default

### ISSUE THREAD

**Issue by kspearrin** [aspnet/StaticFiles#82]
I've got a very simple angualr app project that needs to do nothing more than serve static files from `wwwroot`. Here is my Startup.cs:

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services) { }

        public void Configure(IApplicationBuilder app)
        {
            app.UseIISPlatformHandler();
            app.UseStaticFiles();
        }

        // Entry point for the application.
        public static void Main(string[] args) => WebApplication.Run<Startup>(args);
    }

Whenever I launch the project with IIS Express or web I always have to navigate to `/index.html`. How do I make it so that I can just visit `/` and still get `index.html`?

**Comment by davidfowl** [comment]
Change UseStaticFiles to UseFileServer

**Comment by kspearrin** [comment]
That did it. Thank you.
