### ISSUE TITLE
Am I supposed to use UseSendFileFallback post beta-8?

### ISSUE THREAD

**Issue by jods4** [aspnet/StaticFiles#86]
I upgraded from beta-7 to rc1.

At the end of my pipeline, for any unmatched request, I want to answer with my default application page.
This is meant to enable deep linking in my SPA on the client side.

Anyway, the pipline ends with a call to `app.Run(context => ...)` that basically comes down to:
```csharp
var sendFile = context.Features.Get<IHttpSendFileFeature>();
return sendFile.SendFileAsync("index.html", 0, null, default(CancellationToken));
```

My app was previously hosted in IIS with Helios, but of course this changed when upgrading from beta-7 to rc1. And suddenly it started to break unexpectedly because `sendFile` is `null`.

Questions:

1. Is this expected? I would have thought that the "send file feature" from IIS would maybe flow through, or (more likely) Kestrel would provide its own `IHttpSendFileFeature` (and by that I mean: by default).
2. If this behaviour is intended, then are we supposed to call `app.UseSendFileFallback()`? That was quite unexpected... I would think sending files is major capability of _any_ web server (whether you activate it or not). It should also be noted that I did call `app.UseStaticFiles()` as well somewhere in my startup.
3. Is there any other, simpler way to achieve what I'm doing? I.e. unconditionnally streaming a specific file to any unhandled http request?

**Comment by davidfowl** [comment]
1. Yes it's by design. There's no way to trigger send file via the http platform handler. Doing it with the out of prof hosting would require some kind of header message passing.
2. You don't have to, you can manually fall back. Sending files isn't really a web server function IMO, writing responses is. IHttpSendFileFeature is an optional feature that can be filled in my middleware.
3. Not without writing some code.

**Comment by jods4** [comment]
> 2.You don't have to, you can manually fall back

Do you mean writing my own streaming file logic using `System.IO`? Since you already wrote this, I'm OK reusing your work ;)

Thanks for your confirmation that it's the way to do it from beta-8 onwards, I'm closing this ticket.

I think you might want to clarify the feature matrix that is in the documentation here:
http://docs.asp.net/en/latest/fundamentals/servers.html
Because the IIS columns doesn't make a lot of sense anymore. For instance: yes, IIS has native support for `IHttpSendFileFeature`, but from beta-8 onwards it is my understanding that there is no way to access it from ASP.NET.

**Comment by davidfowl** [comment]
@jods4 Just a heads up we're going to make this easier https://github.com/aspnet/HttpAbstractions/commit/5b175beea877cb6896e50db12060580bfe7e7940

**Comment by jods4** [comment]
Thanks for the info @davidfowl ! 
I'll try that when RC2 is out.

**Comment by jamesgaunt** [comment]
Does this change mean we no longer have access to the IIS "super fast kernel mode (?)" file sending / output caching if a site is running on Kestrel?  This seems like quite a significant loss.

**Comment by davidfowl** [comment]
@jamesgaunt That's correct. You can't directly call into IIS's send file feature anymore. You can use WebListener to get that feature back though (if you need it).

**Comment by jods4** [comment]
@davidfowl Could you provide some links or more details on how using `WebListener` to get back access to IIS native features inside a web application would work out?

**Comment by davidfowl** [comment]
It's not an IIS native feature, it's an `http.sys` native feature (actually there's a sendfile on sockets as well but it's no async). IIS exposes this feature when you run in that process directly. It's fathomable that we expose it via an outgoing header but it's not something we currently plan to support.

If you were relying on this feature I'd like to see the performance metrics you have to show you need that kind of throughput. That's not to say the feature isn't important but it would be to add that scenario to our benchmarks. Its still possible to use IIS to serve static files, but you don't get API level control over that native send file feature.

**Comment by jods4** [comment]
@davidfowl Personnally I was asking just to extend my knowledge of how all of this work. I don't have huge perf requirements on serving files.
