### ISSUE TITLE
Disallow \ (%5C) in path parsing.

### ISSUE THREAD

**Issue by blowdart** [aspnet/StaticFiles#90]
It's not valid in a url path, but on Windows you use it as a directory seperator anyway

e.g. http://localhost:5000/css%5C..%5Ccss%5Csite.min.css

**Comment by Tratcher** [comment]
This happens in two places:
1. Http.Sys will un-escape %5C to `\` and convert it to `/`. This affects all requests through IIS/Express & WebListener. Kestrel will un-escape %5C to `\`, but it does not convert it to `/`.
2. System.IO APIs consider `\` and `/` to be interchangeable in many operations. (At least on Windows. Verify on Mono & CoreCLR).

Neither of these are directly within our control.

**Comment by Tratcher** [comment]
Offline notes: Yes this is strange, but it does not cause any known vulnerabilities. This falls into a similar class of system specific oddities like being case sensitive on linux and not on windows. The Embedded file provider will have similar oddities.
