### ISSUE TITLE
SendFile performance needs investigation

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/StaticFiles#93]
Serving a 512 byte static file:
- From IIS (no caching or compression): 142,203 RPS
- Using SendFile and WebListener: 29,306 RPS

Wouldn't expect the difference to be that high.

**Comment by muratg** [comment]
@DamianEdwards is this only with WebListener?  How does Kestrel compare?

**Comment by Tratcher** [comment]
Kestrel was even worse. This should help Kestrel: https://github.com/aspnet/StaticFiles/issues/91

**Comment by BrennanConroy** [comment]
That did nothing for this scenario that I could see

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.
